# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Joe Meadway - technologist, etc."
email: joemeadway@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The collected notes, snippets and occasionally extended thoughts of Joe Meadway.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://joemeadway.github.io" # the base hostname & protocol for your site
twitter_username: joemeadway
github_username:  joemeadway

repository: joemeadway/joemeadway.github.io

#default YAML settings
permalink: /:year/:month/:day/:title.html


# Build settings
markdown: kramdown
